funct {
   
function myFunction() {
  alert("Hello! I am an alert box!");
  }
}

fun {
    function myFunction() {
        confirm("Press a button!");
      }
}

prom {
  function myFunction() {
    var person = prompt("Please enter your name", "Harry Potter");
    if (person != null) {
      document.getElementById("demo").innerHTML =
      "Hello " + person + "! How are you today?";
    }
  }
}
